<?php
// module/Album/view/album/album/add.phtml:

$title = 'SignUp';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('user', ['action' => 'add']));
$form->prepare();
?>
<div>
	<?= $this->form()->openTag($form);?>
</div>

<div>
	<?= $this->formHidden($form->get('id'));?>
</div>

<div>
	<?= $this->formRow($form->get('firstname'));?>
</div>

<div>
	<?= $this->formRow($form->get('lastname'));?>
</div>

<div>
	<?= $this->formRow($form->get('email')); ?>
</div>

<div>
	<?= $this->formRow($form->get('password')); ?>
</div>

<div>
	<?= $this->formRow($form->get('confirmpassword')); ?>
</div>


<div>
	<?= $this->formSubmit($form->get('submit'));?>
</div>

<div>
	<?php  echo $this->form()->closeTag();?>
</div>

