<?php


$title = 'Add Post';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
    $form->setAttribute('action', $this->url('post', ['action' => 'add']));
    $form->prepare();
?>
	<div>
		<?= $this->form()->openTag($form);?>
	</div>

	<div>
		<?= $this->formHidden($form->get('id'));?>
		<?= $this->formElementErrors($form->get('id'));?>
	</div>

	<div>
		<?= $this->formRow($form->get('title'));?>
		<?php echo $this->formElementErrors($form->get('title'));?>
	</div>

	<div>
		<?= $this->formRow($form->get('category'));?>
		<?= $this->formElementErrors($form->get('category'));?>
	</div>

	<div>
		<?= $this->formRow($form->get('description')); ?>
		<?= $this->formElementErrors($form->get('description'));?>
	</div>


	<div>
		<?= $this->formSubmit($form->get('submit'));?>
	</div>

	<div>
		<?php  echo $this->form()->closeTag();?>
	</div>

