

<?php
$title = 'Add Post';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
	<?php
		$form->setAttribute('action', $this->url('post', ['action' => 'add']));
		$form->prepare();
	?>
	<div>
		<?= $this->form()->openTag($form);?>
	</div>

	<div>
		<?= $this->formHidden($form->get('id'));?>
		<?= $this->formElementErrors($form->get('id'));?>
	</div>

	<div class="form-group">
		<?= $this->formLabel($form->get('title'));?>	
		<div class="col-md-9">
			<?php echo $this->formElement($form->get('title'));?>
			<!-- <div class="alert alert-warning"> -->
			<?php echo  $this->formElementErrors($form->get('title'));?>
			<!-- </div> -->
		</div>
	</div>


	<div class="form-group">
		<?= $this->formLabel($form->get('category'));?>	
		<div class="col-md-9">
			<?php echo $this->formElement($form->get('category'));?>
		    <!-- <div class="alert alert-warning"> -->
			<?php echo $this->formElementErrors($form->get('category'));?>
			<!-- </div>	  -->
		</div>
	</div>


	<div class="form-group">
		<?= $this->formLabel($form->get('description'));?>	
		<div class="col-md-9">
				<?php echo $this->formElement($form->get('description'));?>
			<!-- <div class="alert alert-warning"> -->
				<?php echo $this->formElementErrors($form->get('description'));?>
			<!-- </div> -->
		</div>
	</div>
=

	<div>
		<?= $this->formSubmit($form->get('submit'));?>
	</div>

	<div>
		<?php  echo $this->form()->closeTag();?>
	</div>

