<script
  src="https://code.jquery.com/jquery-3.6.0.slim.js"
  integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
  crossorigin="anonymous"></script>

  <div class="form-outline mb-4">
    <input type="search" class="form-control" id="search" name="search" placeholder="Search">
  </div>
<?php


$title = 'My Post';
$this->headTitle($title);
?>
<?php echo $this->flashMessenger()->render('success',['alert','alert-success']) ?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('post', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Description</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
    <tbody>
        <?php if(!empty($posts)):?>
        <?php for($i=0;$i<count($posts)-1;$i++) : ?>
            <tr>
                <td><?= $this->escapeHtml($posts[$i]['title']) ?></td>
                <td><?= $this->escapeHtml($posts[$i]['category']) ?></td>
                <td><?= $this->escapeHtml($posts[$i]['description']) ?></td>
                <?php if($this->postHelper((int)$posts[$i]['id'])){?>
                <td>
                    <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $posts[$i]['id']]) ?>">Edit</a>
                    <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $posts[$i]['id']]) ?>">Delete</a>
                </td>
                <?php } else{ ?>
                    <td>
                        <p href="">only edited by admin</p>
                        <p href="">only deleted by admin</p>
                    </td>
                <?php  } ?>

            </tr>
        <?php endfor; ?>
        <?php else: for($i=0;$i<1;$i++): ?>
            <tr>
                <td><?= $this->escapeHtml ("There Is No Post") ?></td>
                <td><?= $this->escapeHtml ("There Is No Post") ?></td>
                <td><?= $this->escapeHtml ("There Is No Post") ?></td>
            </tr>
        <?php endfor;?>
        <?php endif;?>
    </tbody>
</table>
    <nav aria-label="Page navigation example">
    
        <ul class="pagination">
            <?php for($i=0;$i<(int)$posts['page'];$i++):?>
                <li class="page-item"><a class="page-link" href="http://localhost:8080/post?page=<?=$i+1?>"><?= $i+1?></a></li>
            <?php endfor;?>
        </ul>
    </nav>
<script src="/js/post.js"></script>